// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	brainy "github.com/Devessier/brainy"
	mock "github.com/stretchr/testify/mock"
)

// Cond is an autogenerated mock type for the Cond type
type Cond struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *Cond) Execute(_a0 brainy.Context, _a1 brainy.Event) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(brainy.Context, brainy.Event) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
